Repository team-abcdedu/abcdedu-backend, pull requests merged in 2024-11, with the labels that each got.

#166 [FIX] #163 postViewCount 증가 로직 적용 불가 버그 수정
  src/main/java/com/abcdedu_backend/post/service/PostService.java
Labels: fix

#170 [refactor] #169 이메일 인증 방식 비동기로 전환
  src/main/java/com/abcdedu_backend/configs/AsyncConfig.java
  src/main/java/com/abcdedu_backend/member/service/EmailService.java
Labels: refactor

#173 [REFACTOR] 이메일 전송 비동기 처리
  src/main/java/com/abcdedu_backend/member/controller/EmailController.java
  src/main/java/com/abcdedu_backend/member/service/EmailSender.java
  src/main/java/com/abcdedu_backend/member/service/EmailService.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
Labels: fix, refactor

#174 [fix] 비동기 제거 누락 수정
  src/main/java/com/abcdedu_backend/member/service/EmailService.java
Labels: fix

#177 [REFACT] #176 어드민 url 분리
  src/main/java/com/abcdedu_backend/contact/controller/AdminContactController.java
  src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
  src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkController.java
  src/main/java/com/abcdedu_backend/homework/controller/HomeworkController.java
  src/main/java/com/abcdedu_backend/survey/controller/AdminSurveyController.java
  src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
Labels: refactor

#175 [Feat] #164 자료실 생성
  src/main/java/com/abcdedu_backend/board/Board.java
  src/main/java/com/abcdedu_backend/board/BoardController.java
  src/main/java/com/abcdedu_backend/board/BoardService.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/dto/request/PostCreateRequestV2.java
  src/main/java/com/abcdedu_backend/post/entity/Post.java
  src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/resources/db/migration/V2__add_boards_document.sql
Labels: feat

#179 [feat] #172 회원 탈퇴 기능 추가
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/resources/db/migration/V2.0.1__add_deleted_column_to_member.sql
  src/test/java/com/abcdedu_backend/member/repository/AdminMemberRepositoryTest.java
  src/test/java/com/abcdedu_backend/member/service/AdminMemberServiceTest.java
Labels: feat

#181 [deploy] 2024-11-14 배포 v1.0.4
  src/main/java/com/abcdedu_backend/board/Board.java
  src/main/java/com/abcdedu_backend/board/BoardController.java
  src/main/java/com/abcdedu_backend/board/BoardService.java
  src/main/java/com/abcdedu_backend/configs/AsyncConfig.java
  src/main/java/com/abcdedu_backend/contact/controller/AdminContactController.java
  src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkController.java
  src/main/java/com/abcdedu_backend/homework/controller/HomeworkController.java
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
  src/main/java/com/abcdedu_backend/member/controller/EmailController.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/member/service/EmailSender.java
  src/main/java/com/abcdedu_backend/member/service/EmailService.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/dto/request/PostCreateRequestV2.java
  src/main/java/com/abcdedu_backend/post/entity/Post.java
  src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/java/com/abcdedu_backend/survey/controller/AdminSurveyController.java
  src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
  src/main/resources/db/migration/V2.0.1__add_deleted_column_to_member.sql
  src/main/resources/db/migration/V2__add_boards_document.sql
  src/test/java/com/abcdedu_backend/member/repository/AdminMemberRepositoryTest.java
  src/test/java/com/abcdedu_backend/member/service/AdminMemberServiceTest.java
Labels: deploy
