Repository team-abcdedu/abcdedu-backend, pull requests merged in 2024-12, with the labels that each got.

#192 [feat] 게시글 조회시 이전,다음 id 추가
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/member/repository/AdminMemberRepository.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/post/dto/PostNavigation.java
  src/main/java/com/abcdedu_backend/post/dto/response/PostResponse.java
  src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
  src/test/java/com/abcdedu_backend/post/service/PostServiceTest.java
Labels: feat

#194 [refactor] 댓글에 첨부파일 첨부 추가
  src/main/java/com/abcdedu_backend/infra/file/FileDirectory.java
  src/main/java/com/abcdedu_backend/post/controller/CommentController.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/dto/response/CommentResponse.java
  src/main/java/com/abcdedu_backend/post/entity/Comment.java
  src/main/java/com/abcdedu_backend/post/service/CommentService.java
  src/main/resources/db/migration/V2.0.2__add_object_key_column_to_comment.sql
Labels: feat

#195 [FEAT] Homework 목록 조회, Table에 날짜 관련 필드 추가
  src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkController.java
  src/main/java/com/abcdedu_backend/homework/dto/response/HomeworkReplyGetRes.java
  src/main/java/com/abcdedu_backend/homework/dto/response/HomeworkRes.java
  src/main/java/com/abcdedu_backend/homework/entity/Homework.java
  src/main/java/com/abcdedu_backend/homework/service/HomeworkService.java
  src/main/resources/db/migration/V2.0.3__add_timestamp_to_homeworks.sql
Labels: feat

#196 [Refact] 설문 도메인 관리자/일반 분리 and DTO 필드명 수정
  src/main/java/com/abcdedu_backend/survey/controller/AdminSurveyController.java
  src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
  src/main/java/com/abcdedu_backend/survey/dto/response/SurveyListResponse.java
  src/main/java/com/abcdedu_backend/survey/service/SurveyService.java
Labels: refactor

#200 [fix] #199 이전,다음 글 secret, writerEmail 추가 및 게시판 구분 추가
  src/main/java/com/abcdedu_backend/post/dto/PostNavigation.java
  src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/test/java/com/abcdedu_backend/post/service/PostServiceTest.java
Labels: fix

#201 [FIX] 스키마 쿼리 H2, MYSQL 용 분리
  src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkController.java
  src/main/java/com/abcdedu_backend/homework/dto/response/HomeworkReplyGetRes.java
  src/main/java/com/abcdedu_backend/homework/dto/response/HomeworkRes.java
  src/main/java/com/abcdedu_backend/homework/entity/Homework.java
  src/main/java/com/abcdedu_backend/homework/service/HomeworkService.java
  src/main/resources/db/migration/V2.0.3__h2__add_timestamp_to_homeworks.sql
  src/main/resources/db/migration/V2.0.3__mysql__add_timestamp_to_homeworks.sql
Labels: fix

#205 [FIX] 파일 없는 댓글 조회시 에러 수정
  src/main/java/com/abcdedu_backend/post/entity/Comment.java
  src/main/java/com/abcdedu_backend/post/service/CommentService.java
Labels: fix

#207 [deploy] 2024-12-11 배포 v1.0.5
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/homework/controller/AdminHomeworkController.java
  src/main/java/com/abcdedu_backend/homework/dto/response/HomeworkReplyGetRes.java
  src/main/java/com/abcdedu_backend/homework/dto/response/HomeworkRes.java
  src/main/java/com/abcdedu_backend/homework/entity/Homework.java
  src/main/java/com/abcdedu_backend/homework/service/HomeworkService.java
  src/main/java/com/abcdedu_backend/infra/file/FileDirectory.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/member/repository/AdminMemberRepository.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/post/controller/CommentController.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/dto/PostNavigation.java
  src/main/java/com/abcdedu_backend/post/dto/response/CommentResponse.java
  src/main/java/com/abcdedu_backend/post/dto/response/PostResponse.java
  src/main/java/com/abcdedu_backend/post/entity/Comment.java
  src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
  src/main/java/com/abcdedu_backend/post/service/CommentService.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/java/com/abcdedu_backend/survey/controller/AdminSurveyController.java
  src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
  src/main/java/com/abcdedu_backend/survey/dto/response/SurveyListResponse.java
  src/main/java/com/abcdedu_backend/survey/service/SurveyService.java
  src/main/resources/db/migration/V2.0.2__add_object_key_column_to_comment.sql
  src/main/resources/db/migration/V2.0.3__add_timestamp_to_homeworks.sql
  src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
  src/test/java/com/abcdedu_backend/post/service/PostServiceTest.java
Labels: deploy

#211 [fix] aws 서버에 기본폰트가 없어 엑셀 파일 추출 중 에러 발생
  Dockerfile
Labels: fix

#213 [fix] #209 post 내용 글자 수 제한 에러
  src/main/resources/db/migration/V2.0.5__change_post_content_length.sql
Labels: fix
