Repository team-abcdedu/abcdedu-backend, pull requests merged in 2024-10, with the labels that each got.

#122 [FEAT] #121 프로메테우스, 그라파나 모니터링 추가
  build.gradle
  deploy.sh
  docker-compose.yml
  prometheus.yml
  src/main/java/com/abcdedu_backend/global/security/SecurityConfig.java
Labels: feat, build

#124 [REFACTOR] #123 Flyway 적용
  build.gradle
  src/main/resources/db/migration/V1__init.sql
Labels: build, refactor

#126 [fix] #125 security jwt 500 에러 해결
  src/main/java/com/abcdedu_backend/global/security/SecurityConfig.java
Labels: fix

#129 [fix] #128 spring security 예외 처리 핸들링 오류 수정
  src/main/java/com/abcdedu_backend/global/security/AuthorizationJwtHeaderFilter.java
  src/main/java/com/abcdedu_backend/global/security/JwtProvider.java
  src/main/java/com/abcdedu_backend/global/security/SecurityConfig.java
Labels: fix

#133 [fix] #132 survey 조회 시, 역할 검증 로직 수정
  src/main/java/com/abcdedu_backend/survey/service/SurveyService.java
Labels: fix

#135 [feat] #134 댓글 조회 기능 변경
  src/main/java/com/abcdedu_backend/post/service/CommentService.java
Labels: feat

#131 [BUILD] #130 AWS 수정사항 적용
  terraform/acm.tf
  terraform/alb.tf
  terraform/sg.tf
  terraform/variables.tf
Labels: build

#146 [DOCS] #142 README.md 작성
  README.md
Labels: docs

#145 [fix] #144 post 조회 시 조회수가 증가가 되지 않는 버그 발견하여 수정
  src/main/java/com/abcdedu_backend/post/entity/Post.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
Labels: fix

#147 [FEAT] #141 관리자 멤버 조회, 일괄 등업 기능 API 명세 merge
  src/main/java/com/abcdedu_backend/member/controller/AdminMemberController.java
  src/main/java/com/abcdedu_backend/member/dto/request/ChangeMemberRoleRequest.java
  src/main/java/com/abcdedu_backend/member/dto/request/MemberSearchCondition.java
  src/main/java/com/abcdedu_backend/member/dto/response/AdminSearchMemberResponse.java
Labels: feat

#150 [FEAT] #139 #140 이메일 인증 및 비밀번호 변경 추가
  build.gradle
  src/main/java/com/abcdedu_backend/configs/EmailConfig.java
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/member/controller/EmailController.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/dto/request/SendEmailCodeRequest.java
  src/main/java/com/abcdedu_backend/member/dto/request/UpdatePasswordRequest.java
  src/main/java/com/abcdedu_backend/member/entity/EmailCode.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/member/repository/EmailCodeRepository.java
  src/main/java/com/abcdedu_backend/member/service/EmailService.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/utils/RandomCodeGenerator.java
  src/test/java/com/abcdedu_backend/member/controller/MemberInfoControllerTest.java
  src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
Labels: feat

#138 [refactor] #137 회원가입시 학번, 학교 추가
  src/main/java/com/abcdedu_backend/member/dto/request/SignUpRequest.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/test/java/com/abcdedu_backend/member/controller/AuthControllerTest.java
  src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
Labels: refactor

#153 [refactor] #152 비밀번호 변경 방식 수정
  src/main/java/com/abcdedu_backend/member/controller/EmailController.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/dto/request/SendMailRequest.java
  src/main/java/com/abcdedu_backend/member/dto/request/UpdatePasswordRequest.java
  src/main/java/com/abcdedu_backend/member/service/EmailService.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/utils/RandomCodeGenerator.java
  src/test/java/com/abcdedu_backend/member/controller/MemberInfoControllerTest.java
Labels: refactor

#158 [fix] #157 회원가입 인증 메시지 제목 수정
  src/main/java/com/abcdedu_backend/member/controller/EmailController.java
  src/main/java/com/abcdedu_backend/member/service/EmailService.java
Labels: fix

#161 [fix] #160 admin 회원가입 api 제거
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/test/java/com/abcdedu_backend/member/controller/AuthControllerTest.java
Labels: fix

#162 [hotfix] 2024-10-30 배포 v1.0.2
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/test/java/com/abcdedu_backend/member/controller/AuthControllerTest.java
Labels: hotfix

#159 [FEAT] #156 등급 일괄 변경 기능
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/member/controller/AdminMemberController.java
  src/main/java/com/abcdedu_backend/member/repository/AdminMemberRepository.java
  src/main/java/com/abcdedu_backend/member/service/AdminMemberService.java
  src/test/java/com/abcdedu_backend/member/repository/AdminMemberRepositoryTest.java
  src/test/java/com/abcdedu_backend/member/service/AdminMemberServiceTest.java
Labels: feat
