Repository team-abcdedu/abcdedu-backend, pull requests merged in 2024-09, with the labels that each got.

#24 [ FIX] cors 에러 해결
  src/main/java/com/abcdedu_backend/configs/WebConfig.java
Labels: fix

#23 [feat] #14 댓글 CRUD 구현
  src/main/java/com/abcdedu_backend/board/Board.java
  src/main/java/com/abcdedu_backend/board/BoardController.java
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/post/PostController.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/dto/request/CommentCreateRequest.java
  src/main/java/com/abcdedu_backend/post/dto/request/CommentUpdateRequest.java
  src/main/java/com/abcdedu_backend/post/dto/response/CommentResponse.java
  src/main/java/com/abcdedu_backend/post/dto/response/PostResponse.java
  src/main/java/com/abcdedu_backend/post/entity/Comment.java
  src/main/java/com/abcdedu_backend/post/entity/Post.java
  src/main/java/com/abcdedu_backend/post/repository/CommentRepository.java
  src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
  src/main/java/com/abcdedu_backend/post/service/CommentService.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
Labels: feat

#26 [FEAT] 상담 기능
  src/main/java/com/abcdedu_backend/configs/RedisConfig.java
  src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
  src/main/java/com/abcdedu_backend/contact/dto/request/ContactCreateRequest.java
  src/main/java/com/abcdedu_backend/contact/dto/response/ContactListResponse.java
  src/main/java/com/abcdedu_backend/contact/dto/response/ContactResponse.java
  src/main/java/com/abcdedu_backend/contact/entity/Contact.java
  src/main/java/com/abcdedu_backend/contact/entity/ContactType.java
  src/main/java/com/abcdedu_backend/contact/repository/ContactRepository.java
  src/main/java/com/abcdedu_backend/contact/service/ContactService.java
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
Labels: feat

#34 [FEAT] #33 로그아웃 api 구현
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
  src/main/java/com/abcdedu_backend/member/repository/RefreshTokenRepository.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/utils/JwtUtil.java
Labels: feat

#32 [FEAT] #20 클래스 등록 및 과제 제출 기능 구현
  .gitignore
  src/main/java/com/abcdedu_backend/common/jwt/JwtValidateArgumentResolver.java
  src/main/java/com/abcdedu_backend/common/jwt/JwtValidation.java
  src/main/java/com/abcdedu_backend/configs/SwaggerConfig.java
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
  src/main/java/com/abcdedu_backend/lecture/dto/CreateAssignmentAnswerDto.java
  src/main/java/com/abcdedu_backend/lecture/dto/QuestionsDto.java
  src/main/java/com/abcdedu_backend/lecture/dto/SubClassDto.java
  src/main/java/com/abcdedu_backend/lecture/dto/request/CreateAssignmentAnswerRequest.java
  src/main/java/com/abcdedu_backend/lecture/dto/request/CreateAssignmentRequest.java
  src/main/java/com/abcdedu_backend/lecture/dto/request/CreateLectureRequest.java
  src/main/java/com/abcdedu_backend/lecture/dto/request/CreateSubLectureRequest.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetAssignmentResponse.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetClassResponse.java
  src/main/java/com/abcdedu_backend/lecture/entity/Assignment.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentAnswer.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentAnswerType.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentQuestion.java
  src/main/java/com/abcdedu_backend/lecture/entity/Lecture.java
  src/main/java/com/abcdedu_backend/lecture/entity/SubLecture.java
  src/main/java/com/abcdedu_backend/lecture/repository/AssignmentAnswerRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/AssignmentQuestionRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/AssignmentRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/LectureRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/SubLectureRepository.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/utils/JwtUtil.java
Labels: feat

#36 [BUILD] #35 프로덕션 환경 구축
  .github/workflows/cicd-prod.yml
  .gitignore
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  terraform/dev/ecr.tf
  terraform/dev/provider.tf
  terraform/ec2.tf
  terraform/ecr.tf
  terraform/elasticache.tf
  terraform/elasticip.tf
  terraform/outputs.tf
  terraform/pemkey.tf
  terraform/provider.tf
  terraform/rds.tf
  terraform/s3.tf
  terraform/sg.tf
  terraform/sh/dev-apply.sh
  terraform/sh/dev-plan.sh
  terraform/sh/prod-apply.sh
  terraform/sh/prod-plan.sh
  terraform/subnet.tf
  terraform/variables.tf
  terraform/vpc.tf
Labels: build

#37 [REFACTOR] #27 POST 기능 고도화(1)
  src/main/java/com/abcdedu_backend/board/BoardController.java
  src/main/java/com/abcdedu_backend/board/BoardService.java
  src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
  src/main/java/com/abcdedu_backend/contact/service/ContactService.java
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/infra/file/FileDirectory.java
  src/main/java/com/abcdedu_backend/infra/file/LocalFileHandler.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/post/controller/CommentController.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/dto/request/PostCreateRequest.java
  src/main/java/com/abcdedu_backend/post/dto/request/PostUpdateRequest.java
  src/main/java/com/abcdedu_backend/post/dto/response/PostListResponse.java
  src/main/java/com/abcdedu_backend/post/entity/Comment.java
  src/main/java/com/abcdedu_backend/post/entity/Post.java
  src/main/java/com/abcdedu_backend/post/repository/PostReposiroty.java
  src/main/java/com/abcdedu_backend/post/service/CommentService.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
Labels: refactor

#49 [FIX] Cors 설정 수정
  .gitignore
  src/main/java/com/abcdedu_backend/configs/WebConfig.java
Labels: fix

#44 [REFACTOR] 평가(시험/이론/실습/프로젝트) api 구현
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  .gitignore
  build.gradle
  src/main/java/com/abcdedu_backend/configs/AwsS3Config.java
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/infra/file/FileDirectory.java
  src/main/java/com/abcdedu_backend/infra/file/FileHandler.java
  src/main/java/com/abcdedu_backend/infra/file/LocalFileHandler.java
  src/main/java/com/abcdedu_backend/infra/file/S3FileHandler.java
  src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
  src/main/java/com/abcdedu_backend/lecture/controller/LectureControllerV2.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetAssignmentAnswerFileUrlResponse.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetAssignmentAnswerResponse.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetAssignmentFileUrlResponse.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetAssignmentResponseV1.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetAssignmentResponseV2.java
  src/main/java/com/abcdedu_backend/lecture/entity/Assignment.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentAnswer.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentAnswerFile.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentFile.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentSubmission.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentType.java
  src/main/java/com/abcdedu_backend/lecture/entity/SubLecture.java
  src/main/java/com/abcdedu_backend/lecture/repository/AssignmentAnswerFileRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/AssignmentFileRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/AssignmentSubmissionRepository.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureServiceV2.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/post/entity/Post.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/resources/application.yaml
Labels: feat

#55 [FIX] resources 폴더 생성 추가
  .github/workflows/cicd-dev.yml
Labels: fix

#56 [FIX] Cookie SameSite 문제 해결
  src/main/java/com/abcdedu_backend/configs/WebConfig.java
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
Labels: fix

#58 [FIX] 쿠키 도메인 수정
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
Labels: fix

#65 [fix] #64 쿠키 도메인 설정 해제
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
Labels: fix

#71 [FIX] 쿠키로 인한 로그인 에러 해결
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
Labels: fix

#72 [FIX] 쿠키로 인한 로그인 에러 해결
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
Labels: fix

#50 [FEAT] 설문 기능 구현
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
  src/main/java/com/abcdedu_backend/survey/dto/request/SurveyChoiceCreateRequest.java
  src/main/java/com/abcdedu_backend/survey/dto/request/SurveyCreateRequest.java
  src/main/java/com/abcdedu_backend/survey/dto/request/SurveyQuestionCreateRequest.java
  src/main/java/com/abcdedu_backend/survey/dto/request/SurveyReplyCreateRequest.java
  src/main/java/com/abcdedu_backend/survey/dto/response/SurveyGetResponse.java
  src/main/java/com/abcdedu_backend/survey/dto/response/SurveyListResponse.java
  src/main/java/com/abcdedu_backend/survey/dto/response/SurveyQuestionChoiceGetResponse.java
  src/main/java/com/abcdedu_backend/survey/dto/response/SurveyQuestionGetResponse.java
  src/main/java/com/abcdedu_backend/survey/dto/response/SurveyRepliesGetResponse.java
  src/main/java/com/abcdedu_backend/survey/entity/Survey.java
  src/main/java/com/abcdedu_backend/survey/entity/SurveyQuestion.java
  src/main/java/com/abcdedu_backend/survey/entity/SurveyQuestionChoice.java
  src/main/java/com/abcdedu_backend/survey/entity/SurveyQuestionType.java
  src/main/java/com/abcdedu_backend/survey/entity/SurveyReply.java
  src/main/java/com/abcdedu_backend/survey/repository/SurveyQuestionChoiceRepository.java
  src/main/java/com/abcdedu_backend/survey/repository/SurveyQuestionRepository.java
  src/main/java/com/abcdedu_backend/survey/repository/SurveyReplyRepository.java
  src/main/java/com/abcdedu_backend/survey/repository/SurveyRepository.java
  src/main/java/com/abcdedu_backend/survey/service/SurveyService.java
Labels: feat

#63 [FEAT] 클래스 기능 추가
  src/main/java/com/abcdedu_backend/infra/file/FileDirectory.java
  src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
  src/main/java/com/abcdedu_backend/lecture/controller/LectureControllerV2.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentAnswerFile.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentFile.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentType.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/main/java/com/abcdedu_backend/member/controller/AuthController.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
Labels: feat

#80 [REFACTOR] #76 클래스 정보 변경
  src/main/java/com/abcdedu_backend/lecture/dto/request/CreateLectureRequest.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetClassResponse.java
  src/main/java/com/abcdedu_backend/lecture/entity/Lecture.java
  src/main/java/com/abcdedu_backend/lecture/entity/SubLecture.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureServiceV2.java
Labels: refactor

#74 [FEAT] 멤버 도메인 테스트코드 작성
  build.gradle
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/infra/file/FileHandler.java
  src/main/java/com/abcdedu_backend/infra/file/LocalFileHandler.java
  src/main/java/com/abcdedu_backend/infra/file/S3FileHandler.java
  src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/dto/response/MemberNameAndRoleResponse.java
  src/main/java/com/abcdedu_backend/member/entity/Member.java
  src/main/java/com/abcdedu_backend/member/repository/MemberRepository.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/java/com/abcdedu_backend/utils/FileUtil.java
  src/test/java/com/abcdedu_backend/member/controller/AuthControllerTest.java
  src/test/java/com/abcdedu_backend/member/controller/MemberInfoControllerTest.java
  src/test/java/com/abcdedu_backend/member/repository/MemberRepositoryTest.java
  src/test/java/com/abcdedu_backend/member/repository/RefreshTokenRepositoryTest.java
  src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
Labels: feat

#86 [FIX] 레디스 및 테스트 환경 설정
  build.gradle
  src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/test/java/com/abcdedu_backend/config/RedisTestContainer.java
  src/test/java/com/abcdedu_backend/member/repository/RefreshTokenRepositoryTest.java
Labels: fix

#92 [REFACTOR] #91 파일 업로드 로직 성능 개선
  src/main/java/com/abcdedu_backend/infra/file/FileHandler.java
  src/main/java/com/abcdedu_backend/infra/file/LocalFileHandler.java
  src/main/java/com/abcdedu_backend/infra/file/S3FileHandler.java
  src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/java/com/abcdedu_backend/utils/FileUtil.java
  src/test/java/com/abcdedu_backend/member/controller/MemberInfoControllerTest.java
  src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
Labels: refactor

#96 [FIX] #93 게시글 관련 오류 해결
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
Labels: fix

#99 [FEAT] 멤버 기본 정보 조회 API 구현
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/dto/response/MemberBasicInfoResponse.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/test/java/com/abcdedu_backend/member/controller/MemberInfoControllerTest.java
  src/test/java/com/abcdedu_backend/member/service/MemberServiceTest.java
Labels: feat

#101 [REFACTOR] 운영 배포 전 리팩터링
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentFile.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentType.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/main/java/com/abcdedu_backend/member/dto/response/MemberInfoResponse.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
Labels: refactor

#113 [FIX] 9월 22일 이후 변경된 요구사항 반영
  src/main/java/com/abcdedu_backend/board/BoardController.java
  src/main/java/com/abcdedu_backend/common/page/PageManager.java
  src/main/java/com/abcdedu_backend/common/page/request/PagingRequest.java
  src/main/java/com/abcdedu_backend/common/page/request/SortRequest.java
  src/main/java/com/abcdedu_backend/common/page/response/PagedResponse.java
  src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
  src/main/java/com/abcdedu_backend/infra/file/S3FileHandler.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/dto/response/PostListResponse.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
Labels: fix

#117 [deploy] 2024-09-25 운영 서버 배포 v1.0
  src/main/java/com/abcdedu_backend/board/BoardController.java
  src/main/java/com/abcdedu_backend/common/page/PageManager.java
  src/main/java/com/abcdedu_backend/common/page/request/PagingRequest.java
  src/main/java/com/abcdedu_backend/common/page/request/SortRequest.java
  src/main/java/com/abcdedu_backend/common/page/response/PagedResponse.java
  src/main/java/com/abcdedu_backend/contact/controller/ContactController.java
  src/main/java/com/abcdedu_backend/infra/file/S3FileHandler.java
  src/main/java/com/abcdedu_backend/post/controller/PostController.java
  src/main/java/com/abcdedu_backend/post/dto/response/PostListResponse.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/java/com/abcdedu_backend/survey/controller/SurveyController.java
Labels: deploy

#115 [Feat] 새싹 회원 검증 로직 추가
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/main/java/com/abcdedu_backend/post/service/PostService.java
  src/main/java/com/abcdedu_backend/survey/service/SurveyService.java
Labels: refactor

#119 [TEST] 클래스 테스트코드 작성 및 리팩터링
  src/main/java/com/abcdedu_backend/exception/ErrorCode.java
  src/main/java/com/abcdedu_backend/global/security/AuthorizationJwtHeaderFilter.java
  src/main/java/com/abcdedu_backend/infra/file/FileDirectory.java
  src/main/java/com/abcdedu_backend/lecture/controller/AdminLectureController.java
  src/main/java/com/abcdedu_backend/lecture/controller/LectureController.java
  src/main/java/com/abcdedu_backend/lecture/dto/SubClassDto.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetAssignmentFileUrlResponse.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetAssignmentResponseV1.java
  src/main/java/com/abcdedu_backend/lecture/dto/response/GetClassResponse.java
  src/main/java/com/abcdedu_backend/lecture/entity/Assignment.java
  src/main/java/com/abcdedu_backend/lecture/entity/AssignmentType.java
  src/main/java/com/abcdedu_backend/lecture/entity/SubLecture.java
  src/main/java/com/abcdedu_backend/lecture/entity/v2/AssignmentAnswer.java
  src/main/java/com/abcdedu_backend/lecture/entity/v2/AssignmentAnswerType.java
  src/main/java/com/abcdedu_backend/lecture/entity/v2/AssignmentQuestion.java
  src/main/java/com/abcdedu_backend/lecture/entity/v2/AssignmentSubmission.java
  src/main/java/com/abcdedu_backend/lecture/repository/AssignmentAnswerFileRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/AssignmentFileRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/SubLectureRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/v2/AssignmentAnswerRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/v2/AssignmentQuestionRepository.java
  src/main/java/com/abcdedu_backend/lecture/repository/v2/AssignmentSubmissionRepository.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/main/java/com/abcdedu_backend/lecture/service/LectureServiceV2.java
  src/main/java/com/abcdedu_backend/member/controller/MemberInfoController.java
  src/main/java/com/abcdedu_backend/member/service/MemberService.java
  src/test/java/com/abcdedu_backend/lecture/controller/AdminLectureControllerTest.java
  src/test/java/com/abcdedu_backend/lecture/controller/LectureControllerTest.java
  src/test/java/com/abcdedu_backend/lecture/service/LectureServiceTest.java
Labels: refactor

#120 [FIX] errorCode 충돌 해결
  src/main/java/com/abcdedu_backend/lecture/service/LectureService.java
  src/test/java/com/abcdedu_backend/lecture/controller/LectureControllerTest.java
Labels: fix
